### PR TITLE
Development Pulling request

### PR DESCRIPTION
**Pull request by aron-net**
-  editing the readme file for a proper project name, and description, social media links, and major language.
- editing the linter file  hintrc and stylelintrc.

### CODE REVIEW

**Review by OLIPLICHE — CHANGES_REQUESTED** [review]
Hi @aron-helu , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

✅
- README file is descriptive 👏
- Commit messages are meaningful 👏 👏
- Github flow is correctly used (Pull Request is made from the feature branch into the main branch) 👏
 ## Required Changes ♻️

- [ ] Please, need to set up the Linter in your project. Open this link and follow the steps in there: [LINTER CONFIGURATION](https://github.com/microverseinc/linters-config/tree/master/html-css)

_Check the comments under the review._

## Optional suggestions

- [ ] Please, in your next commit, make sure to use **imperative tense and capitalized**. Open this link to learn more:  [Descriptive commit messages](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md)
- [ ] Please, the Pull Request should have a descriptive title. Kindly open this link and learn: [Write a meaningful title for your pull request](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by OLIPLICHE** [comment]
- [x] Please don't delete the branch, don't change and don't merge it as well till everything is complete.

**Comment by aron-net** [comment]
linter has been installed

**Comment by OLIPLICHE** [comment]
- [x]  Please, I checked the linter files and everything is up to date. I realized that you have a lot of files ignored inside `.gitignore`, and maybe that is where the issue is coming from. 
- [x] I suggest that next time, you should send inside the "gitignore" file only "node_modules" and "test.md" and forget the rest.
- [x] I confirm that your linter files are up to date. Please submit your pull request, the next reviewer might suggest something and approve your project. All the best

**Review by chrystalme — CHANGES_REQUESTED** [review]
# Hi @aron-helu , 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Highlights 💡 
- .hintrc added to project ✅ 
- .stylelintrc.json added to project ✅ 

## Suggested changes ♻️ 
Kindly put your `linters.yml` inside another folder called `workflows` which should be inside `.github`. Your directory structure should be `.github/workflows/linters.yml` but now it is `.github/linters.yml`.

## Optional requirements
- Kindly start your git comments with a capital letter. This make your comments more professional.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Also, you can reach me on [Twitter](https://twitter.com/afam_ifeanyi) or [Slack](https://microverse-community.slack.com/team/U019ZC99KFA). Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by KayLemba — APPROVED** [review]
# STATUS: APPROVED :green_circle: :clap: 

Hello  @aron-helu   , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

HIGHLIGHTS:

- Your project is professional 
- Your repo is professional 
- Well structured files


Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

well-1

[OPTIONAL] Kindly add a screenshot to your README file showing your webpage user Interface. You can use extentions like fireshot to capturer the entire page.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
